PedroHTomaz/beacademy-devstart-safira

projeto-empresarial/resources/views/admin-login.blade.php, projeto-empresarial/routes/web.php
=> view admin added

projeto-empresarial/app/Http/Controllers/ProductController.php, projeto-empresarial/app/Http/Requests/CreateProductFormRequest.php, projeto-empresarial/app/Models/Product.php, projeto-empresarial/database/migrations/2022_06_29_182548_create_products_table.php, projeto-empresarial/resources/views/product/add-product.blade.php, projeto-empresarial/routes/web.php
Criacao de rota e metodo para inserir dados na base referente ao produtos
=> Registro de  produto na banco de dados

projeto-empresarial/app/Http/Controllers/ProductController.php, projeto-empresarial/app/Http/Controllers/UserController.php, projeto-empresarial/app/Models/Registered.php, projeto-empresarial/database/migrations/2022_07_02_135950_create_registereds_table.php, projeto-empresarial/resources/views/users/create.blade.php, projeto-empresarial/routes/web.php
Requisição e cadastro de usuário no banco. Falta a listagem de usuários.
=> Requisicao e cadastro de usuario no banco

projeto-empresarial/resources/views/index.blade.php, projeto-empresarial/resources/views/layouts/template.blade.php, projeto-empresarial/resources/views/product/add-product.blade.php, projeto-empresarial/resources/views/product/edit.blade.php, projeto-empresarial/resources/views/product/index.blade.php, projeto-empresarial/resources/views/product/show.blade.php, projeto-empresarial/resources/views/users/create.blade.php, projeto-empresarial/vite.config.js
Todas views padronizadas com o design da home.
As mudanças não possuem edições de lógica, logo, é seguro priorizar o merge desta branch.
=> padronizando design do website

projeto-empresarial/app/Http/Controllers/AdminController.php, projeto-empresarial/resources/views/index.blade.php
Poderiam realizar o review dessas pequenas correções.
=> fixing admin.index and users.create routes

projeto-empresarial/resources/views/layouts/template.blade.php, projeto-empresarial/resources/views/users/admin-login.blade.php, projeto-empresarial/resources/views/users/create.blade.php
Input Cep posicionado como primeira info nos dados de endereço pra api viacep fazer o resto do trabalho
=> input cep priorizado na secao endereco no cadastro

projeto-empresarial/app/Http/Controllers/ProductController.php, projeto-empresarial/resources/views/product/show.blade.php, projeto-empresarial/routes/web.php
=> deleting products

projeto-empresarial/app/Providers/AppServiceProvider.php, projeto-empresarial/resources/views/errors/404.blade.php
View errors > 404 adicionada e funcional
=> view 404 adicionada

projeto-empresarial/app/Http/Controllers/Auth/AuthenticatedSessionController.php, projeto-empresarial/app/Http/Controllers/Auth/RegisteredUserController.php, projeto-empresarial/app/Providers/RouteServiceProvider.php
Redirecionando cliente para pagina de catologo e admin para pagina de dashboard
=> redirecting client to catalog page and admin to dashboard page

projeto-empresarial/resources/views/layouts/template-main.blade.php, projeto-empresarial/resources/views/product/list.blade.php, projeto-empresarial/resources/views/users/edit.blade.php
Se o login for !== (diferente) de is_admin, um carrinho será adicionado à navbar do usuário na view de catálogo
=> carrinho adicionado a navbar

projeto-empresarial/app/Http/Controllers/ProductController.php, projeto-empresarial/public/assets/js/cart.js, projeto-empresarial/resources/views/layouts/template-main.blade.php, projeto-empresarial/resources/views/product/carrinho.blade.php, projeto-empresarial/resources/views/product/list.blade.php, projeto-empresarial/resources/views/users/edit.blade.php, projeto-empresarial/resources/views/welcome.blade.php, projeto-empresarial/routes/web.php
Carrinho em produção, porém necessitando de tratamento backend.
=> carrinho-layout, porem sem backend

projeto-empresarial/app/Http/Controllers/Auth/RegisteredUserController.php, projeto-empresarial/resources/views/welcome.blade.php, projeto-empresarial/routes/web.php
Quando criamos a autenticação a parte de salvar a foto do perfil do usuário no banco tinha quebrado.
=> fixing to save profile pictures in the database

projeto-empresarial/app/Http/Controllers/CartController.php, projeto-empresarial/app/Http/Controllers/UserController.php, projeto-empresarial/app/Models/OrderProduct.php, projeto-empresarial/app/Models/Orders.php, projeto-empresarial/app/Models/Product.php, projeto-empresarial/database/migrations/2022_07_18_121831_drop_columns_product_id_and_value_and_status_to_orders_table.php, projeto-empresarial/database/migrations/2022_07_18_122716_add_field_status_to_orders_table.php, projeto-empresarial/database/migrations/2022_07_18_142638_create_order_products_table.php, projeto-empresarial/resources/views/product/list.blade.php, projeto-empresarial/routes/web.php
=> creating migrations and models of orders and order_products

projeto-empresarial/resources/views/errors/404.blade.php, projeto-empresarial/resources/views/product/carrinho.blade.php
Layout do carrinho corrigido e uma rota de retorno ao catálogo adicionada caso o carrinho esteja vazio.
=> layout do carrinho consertado

projeto-empresarial/resources/views/product/list.blade.php
Margem inferior adicionada aos cards na view catálogo
=> margem adicionada ao catalogo

projeto-empresarial/app/Http/Controllers/OrdersContoller.php, projeto-empresarial/app/Models/Orders.php, projeto-empresarial/resources/views/orders/edit.blade.php, projeto-empresarial/resources/views/orders/index.blade.php, projeto-empresarial/resources/views/orders/show.blade.php
Corrigi a visualização de pedidos pelo o administrador
=> fixing order list for admin

README.md, projeto-empresarial/resources/views/users/edit.blade.php, projeto-empresarial/routes/web.php, projeto-empresarial/tests/Feature/DeleteProductTest.php, projeto-empresarial/tests/Feature/EditProductTest.php, projeto-empresarial/tests/Feature/UserDeleteTest.php, projeto-empresarial/tests/Feature/UserEditTest.php
Testes - Deletar e Editar Usuários e Produtos. Tudo conforme previsto.
=> Tests/ Delete e Edit Users and Products

projeto-empresarial/public/assets/js/confirmDelete.js, projeto-empresarial/resources/views/cart/carrinho.blade.php, projeto-empresarial/resources/views/cart/checkout.blade.php, projeto-empresarial/resources/views/dashboard/orders.blade.php, projeto-empresarial/resources/views/dashboard/product.blade.php, projeto-empresarial/resources/views/dashboard/users.blade.php, projeto-empresarial/resources/views/layouts/template-admin.blade.php, projeto-empresarial/resources/views/layouts/template-main.blade.php, projeto-empresarial/resources/views/layouts/template.blade.php, projeto-empresarial/resources/views/orders/show.blade.php, projeto-empresarial/resources/views/product/list.blade.php, projeto-empresarial/resources/views/product/show.blade.php, projeto-empresarial/resources/views/suport/contact.blade.php, projeto-empresarial/resources/views/users/show.blade.php
algumas linhas de código a mais para dar mais segurança para o admin ao chamar o método destroy
=> adicionada mais seguranca no metodo destroy de user, product e orders

projeto-empresarial/app/Http/Controllers/CartController.php, projeto-empresarial/app/Http/Controllers/OrdersContoller.php, projeto-empresarial/app/Http/Controllers/ProductController.php, projeto-empresarial/app/Models/OrderProduct.php, projeto-empresarial/resources/views/cart/checkout.blade.php, projeto-empresarial/resources/views/orders/edit.blade.php, projeto-empresarial/resources/views/orders/show.blade.php, projeto-empresarial/routes/web.php
Melhorei como o admininstrador visualiza os pedidos
=> organizing order listing for admin

projeto-empresarial/app/Http/Requests/CreateProductFormRequest.php, projeto-empresarial/resources/views/product/edit.blade.php
Estava sendo obrigatório atualizar a foto toda vez que fosse atualizar qualquer campo do produto, então retirei do request de produtos a obrigatoriedade de preencher o campo foto, retirei o required do form de editar produto e deixei somente o required no campo img no form de criar produtos.
=> Fix edit products photo

app/Http/Controllers/Auth/RegisteredUserController.php
Validação impedindo cep com zero no primeiro dígito - consertado
=> cep aceitando zero como primeiro digito

app/Http/Controllers/ApiCheckoutController.php, package-lock.json, resources/views/cart/checkout.blade.php, resources/views/cart/ticket.blade.php, resources/views/orders/concluded.blade.php, resources/views/squad/profile.blade.php, resources/views/suport/payment.blade.php, routes/web.php
Corrigindo algumas coisas que quebraram
=> correcting image bugs, ticket view and personal pitch
